repos:
  - repo: local
    hooks:
      - id: php-cs-fixer
        name: PHP CS Fixer
        entry: ./vendor/bin/php-cs-fixer fix --dry-run --diff
        language: system
        files: \.php$
        pass_filenames: false

      - id: phpstan
        name: PHPStan
        entry: ./vendor/bin/phpstan analyse
        language: system
        files: \.php$
        pass_filenames: false

      - id: phpunit
        name: PHPUnit Tests
        entry: ./vendor/bin/phpunit
        language: system
        files: \.php$
        pass_filenames: false